# Generated by Django 6.0.1 on 2026-02-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chef',
            new_name='Chefs',
        ),
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Testimonials',
        ),
    ]
