# Generated by Django 6.0.2 on 2026-02-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
