# Generated by Django 6.0.1 on 2026-02-06 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0002_rename_chef_chefs_rename_testimonial_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chefs',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chefs',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='chefs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonials',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
