# Generated by Django 6.0.1 on 2026-02-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0003_chefs_created_at_chefs_priority_chefs_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='customer_name',
            new_name='name',
        ),
    ]
