# Generated by Django 6.0.1 on 2026-02-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0005_alter_testimonials_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chefs',
            new_name='Teams',
        ),
    ]
