# Generated by Django 6.0 on 2026-04-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pidx',
            new_name='payment_id',
        ),
    ]
