# Generated by Django 6.0 on 2026-04-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_panel', '0002_rename_name_testimonials_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Reviews',
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='reviews',
        ),
    ]
