# Generated by Django 6.0.1 on 2026-03-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_panel', '0002_otp_remove_teams_priority_remove_teams_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
