# Generated by Django 6.0.1 on 2026-03-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pages', '0002_alter_teams_slug_alter_testimonials_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='image',
        ),
    ]
