# Generated by Django 6.0 on 2026-03-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('ended', 'Ended'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
