# Generated by Django 6.0 on 2026-05-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('ended', 'Ended'), ('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
