# Generated by Django 6.0 on 2026-04-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_booking_status_alter_booking_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ended', 'Ended')], default='pending', max_length=20),
        ),
    ]
