# Generated by Django 6.0 on 2026-05-02 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_booking_date_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('ended', 'Ended'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
