# Generated by Django 6.0 on 2026-05-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_booking_date_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('ended', 'Ended'), ('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
    ]
