# Generated by Django 6.0 on 2026-05-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ended', 'Ended'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
    ]
