# Generated by Django 6.0 on 2026-05-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('ended', 'Ended'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
