# Generated by Django 6.0.2 on 2026-02-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table='shipping_addresses',
        ),
    ]
