# Generated by Django 6.0 on 2026-05-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20),
        ),
    ]
