# Generated by Django 6.0 on 2026-04-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
