# Generated by Django 6.0.1 on 2026-03-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
