# Generated by Django 6.0 on 2026-05-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_orderitem_options_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20),
        ),
    ]
