# Generated by Django 6.0 on 2026-05-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20),
        ),
    ]
